# Generated by Django 5.0.6 on 2024-07-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_category_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='updated_at',
        ),
    ]
