# Generated by Django 5.0.7 on 2024-08-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_type',
            field=models.CharField(default='article', max_length=50),
        ),
    ]
