# Generated by Django 5.1.1 on 2024-10-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_outline',
            field=models.TextField(blank=True, help_text='Course Outline, separate each item with a newline', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='includes',
            field=models.TextField(blank=True, help_text='This course includes, separate each item with a newline', null=True),
        ),
    ]
